package edu.utsa.cs4593.inventree.model;

public class Category {

    /*
     * TODO: THIS CLASS IS SUPPOSED TO LOOK THROUGH ALL THE PRODUCT
     *  OBJECTS AND THEN BE ABLE TO MAKE AN ARRAY LIST OF ALL THE
     *  POSSIBLE CATEGORIES, IF THEY REPEAT THEY WILL NOT BE ADDED AGAIN
     *
     * THIS IS SO THAT USER IN FILTER SEARCH PRODUCT CATEGORY
     * CAN LOOK THROUGH AND CHOSE THROUGH THERE
     */
}
