package edu.utsa.cs4593.inventree.model;

public class Location {

    //TODO: THIS CLASS IS SUPPOSED TO LOOK THROUGH THE PRODUCTS
    // OR PRODUCT OBJECTS AND GET ALL THE DIFFERENT LOCATIONS INTO
    // AN ARRY LIST ARRAY, IF THE LOCATION REPEATS IT IS NOT ADDED

    // TODO: THIS IS SO THAT FILTER SEARCH PRODUCT LOCATION DROPDOWN
    //  LOADS ALL THE LOCATION OPTIONS INTO THE DROP DOWN AND
    //  USER CAN SELECT FROM IT
}
